<script setup lang="ts">
import { Ref, ref } from 'vue';
import { useLocal } from '@/process/UseLocal.ts';
import MyHeader from '@/components/My-Header.vue';
import TimeTable from '@/components/TimeTable.vue';
import DiaryElement from '@/components/DiaryElement.vue';
import SetMarks from '@/components/setMarks.vue';
import { Lesson } from '@/types.ts';
import AuthenticationForm from '@/components/ui/AuthenticationForm.vue';

useLocal();

const les: Ref<Lesson[]> = ref([
  {
    id: 123,
    lessonId: 1,
    callStart: '8:45',
    callEnd: '9:45',
    name: 'Урок урока',
    cabinet: 'Кабинет урока уроковича',
    current: 'Изучение урока',
    homeWork: 'Домашука урока уроковича',
    mark: 2,
    teacher: 'Клавида петровна2',
  },
  {
    id: 5,
    lessonId: 2,
    callStart: '8:45',
    callEnd: '9:45',
    name: '212qwdadwa',
    cabinet: '3',
    teacher: 'Клавида петровна2',

    current: '4',
    homeWork: '5',
    mark: 9,
  },
  {
    id: 45,
    lessonId: 3,
    callStart: '8:45',
    callEnd: '78:45',
    name: '31321dsa',
    cabinet: 'Кабінеxzxxcz ії[36]',
    current: '44',
    homeWork: '44',
    teacher: 'Клавида петровна2',

    mark: 6,
  },
  {
    id: 1,
    lessonId: 4,
    callStart: '8:45',
    callEnd: '9:45',
    name: '31321dsa',
    cabinet: 'Кабінет географії[36]',
    current: '5',
    homeWork: '6',
    teacher: 'Клавида петровна2',
    mark: 10,
  },
]);
const days = ref([
  {
    id: 1,
    date: '03.06.24',
    subjects: [
      {
        id: 5,
        lessonId: 2,
        callStart: '8:45',
        callEnd: '9:45',
        name: '1 урока',
        cabinet: '3',
        teacher: 'Клавида петровна2',
        current: '4',
        homeWork: '5',
        mark: 9,
      },
      {
        id: 45,
        lessonId: 3,
        callStart: '8:45',
        callEnd: '78:45',
        name: '31321dsa',
        cabinet: 'Кабінеxzxxcz ії[36]',
        current: '44',
        homeWork: '44',
        teacher: 'Клавида петровна4',
        mark: 6,
      },
      {
        id: 1,
        lessonId: 4,
        callStart: '8:45',
        callEnd: '9:45',
        name: '31321dsa',
        cabinet: 'Кабінет географії[36]',
        current: '5',
        teacher: 'Клавида петровна6',
        homeWork: '6',
        mark: 10,
      },
      {
        id: 1,
        lessonId: 4,
        callStart: '8:45',
        callEnd: '9:45',
        name: '31321dsa',
        cabinet: 'Кабінет географії[36]',
        current: '5',
        teacher: 'Клавида петровна6',
        homeWork: '6',
        mark: 10,
      },
      {
        id: 1,
        lessonId: 4,
        callStart: '8:45',
        callEnd: '9:45',
        name: '31321dsa',
        cabinet: 'Кабінет географії[36]',
        current: '5',
        teacher: 'Клавида петровна6',
        homeWork: '6',
        mark: 10,
      },
      {
        id: 1,
        lessonId: 4,
        callStart: '8:45',
        callEnd: '9:45',
        name: '31321dsa',
        cabinet: 'Кабінет географії[36]',
        current: '5',
        teacher: 'Клавида петровна6',
        homeWork: '6',
        mark: 10,
      },
      {
        id: 1,
        lessonId: 4,
        callStart: '8:45',
        callEnd: '9:45',
        name: '31321dsa',
        cabinet: 'Кабінет географії[36]',
        current: '5',
        teacher: 'Клавида петровна6',
        homeWork: '6',
        mark: 10,
      },
    ],
  },
  {
    id: 2,
    date: '04.06.24',
    subjects: [
      {
        id: 123,
        lessonId: 1,
        callStart: '8:45',
        callEnd: '9:45',
        name: 'Урок урока',
        cabinet: 'Кабинет урока уроковича',
        current: 'Изучение урока',
        homeWork: 'Домашука урока уроковича',
        teacher: 'Клавида петровна',
        mark: 2,
      },
      {
        id: 5,
        lessonId: 2,
        callStart: '8:45',
        callEnd: '9:45',
        name: '212qwdadwa',
        cabinet: '3',
        teacher: 'Клавида петровна2',
        current: '4',
        homeWork: '5',
        mark: 9,
      },
      {
        id: 45,
        lessonId: 3,
        callStart: '8:45',
        callEnd: '78:45',
        name: '31321dsa',
        cabinet: 'Кабінеxzxxcz ії[36]',
        current: '44',
        homeWork: '44',
        teacher: 'Клавида петровна4',
        mark: 6,
      },
      {
        id: 1,
        lessonId: 4,
        callStart: '8:45',
        callEnd: '9:45',
        name: '31321dsa',
        cabinet: 'Кабінет географії[36]',
        current: '5',
        teacher: 'Клавида петровна6',
        homeWork: '6',
        mark: 10,
      },
      {
        id: 1,
        lessonId: 4,
        callStart: '8:45',
        callEnd: '9:45',
        name: '31321dsa',
        cabinet: 'Кабінет географії[36]',
        current: '5',
        teacher: 'Клавида петровна6',
        homeWork: '6',
        mark: 10,
      },
      {
        id: 1,
        lessonId: 4,
        callStart: '8:45',
        callEnd: '9:45',
        name: '31321dsa',
        cabinet: 'Кабінет географії[36]',
        current: '5',
        teacher: 'Клавида петровна6',
        homeWork: '6',
        mark: 10,
      },
      {
        id: 1,
        lessonId: 4,
        callStart: '8:45',
        callEnd: '9:45',
        name: '31321dsa',
        cabinet: 'Кабінет географії[36]',
        current: '5',
        teacher: 'Клавида петровна6',
        homeWork: '6',
        mark: 10,
      },
    ],
  },
  {
    id: 3,
    date: '05.06.24',
    subjects: [
      {
        teacher: 'Клавида петровна',
        id: 123,
        lessonId: 1,
        callStart: '8:45',
        callEnd: '9:45',
        name: 'Урок урока',
        cabinet: 'Кабинет урока уроковича',
        current: 'Изучение урока',
        homeWork: 'Домашука урока уроковича',
        mark: 2,
      },
      {
        teacher: 'Клавида петровна',
        id: 5,
        lessonId: 2,
        callStart: '8:45',
        callEnd: '9:45',
        name: '212qwdadwa',
        cabinet: '3',
        current: '4',
        homeWork: '5',
        mark: 9,
      },
      {
        teacher: 'Клавида петровна',
        id: 45,
        lessonId: 3,
        callStart: '8:45',
        callEnd: '78:45',
        name: '31321dsa',
        cabinet: 'Кабінеxzxxcz ії[36]',
        current: '44',
        homeWork: '44',
        mark: 6,
      },
      {
        id: 123,
        lessonId: 4,
        callStart: '8:45',
        callEnd: '9:45',
        name: 'Урок урока',
        cabinet: 'Кабинет урока уроковича',
        current: 'Изучение урока',
        homeWork: 'Домашука урока уроковича',
        teacher: 'Клавида петровна',
        mark: 2,
      },
      {
        teacher: 'Клавида петровна',
        id: 1,
        lessonId: 5,
        callStart: '8:45',
        callEnd: '9:45',
        name: '31321dsa',
        cabinet: 'Кабінет географії[36]',
        current: '5',
        homeWork: '6',
        mark: 10,
      },
      {
        teacher: 'Клавида петровна',
        id: 1,
        lessonId: 5,
        callStart: '8:45',
        callEnd: '9:45',
        name: '31321dsa',
        cabinet: 'Кабінет географії[36]',
        current: '5',
        homeWork: '6',
        mark: 10,
      },
    ],
  },
  {
    id: 3,
    date: '06.06.24',
    subjects: [
      {
        teacher: 'Клавида петровна',
        id: 123,
        lessonId: 1,
        callStart: '8:45',
        callEnd: '9:45',
        name: 'Урок урока',
        cabinet: 'Кабинет урока уроковича',
        current: 'Изучение урока',
        homeWork: 'Домашука урока уроковича',
        mark: 2,
      },
      {
        teacher: 'Клавида петровна',
        id: 5,
        lessonId: 2,
        callStart: '8:45',
        callEnd: '9:45',
        name: '212qwdadwa',
        cabinet: '3',
        current: '4',
        homeWork: '5',
        mark: 9,
      },
      {
        teacher: 'Клавида петровна',
        id: 45,
        lessonId: 3,
        callStart: '8:45',
        callEnd: '78:45',
        name: '31321dsa',
        cabinet: 'Кабінеxzxxcz ії[36]',
        current: '44',
        homeWork: '44',
        mark: 6,
      },
      {
        id: 123,
        lessonId: 4,
        callStart: '8:45',
        callEnd: '9:45',
        name: 'Урок урока',
        cabinet: 'Кабинет урока уроковича',
        current: 'Изучение урока',
        homeWork: 'Домашука урока уроковича',
        teacher: 'Клавида петровна',
        mark: 2,
      },
      {
        teacher: 'Клавида петровна',
        id: 1,
        lessonId: 5,
        callStart: '8:45',
        callEnd: '9:45',
        name: '31321dsa',
        cabinet: 'Кабінет географії[36]',
        current: '5',
        homeWork: '6',
        mark: 10,
      },
      {
        teacher: 'Клавида петровна',
        id: 1,
        lessonId: 5,
        callStart: '8:45',
        callEnd: '9:45',
        name: '31321dsa',
        cabinet: 'Кабінет географії[36]',
        current: '5',
        homeWork: '6',
        mark: 10,
      },
    ],
  },
  {
    id: 3,
    date: '07.06.24',
    subjects: [
      {
        teacher: 'Клавида петровна',
        id: 123,
        lessonId: 1,
        callStart: '8:45',
        callEnd: '9:45',
        name: 'Урок урока',
        cabinet: 'Кабинет урока уроковича',
        current: 'Изучение урока',
        homeWork: 'Домашука урока уроковича',
        mark: 2,
      },
      {
        teacher: 'Клавида петровна',
        id: 5,
        lessonId: 2,
        callStart: '8:45',
        callEnd: '9:45',
        name: '212qwdadwa',
        cabinet: '3',
        current: '4',
        homeWork: '5',
        mark: 9,
      },
      {
        teacher: 'Клавида петровна',
        id: 45,
        lessonId: 3,
        callStart: '8:45',
        callEnd: '78:45',
        name: '31321dsa',
        cabinet: 'Кабінеxzxxcz ії[36]',
        current: '44',
        homeWork: '44',
        mark: 6,
      },
      {
        id: 123,
        lessonId: 4,
        callStart: '8:45',
        callEnd: '9:45',
        name: 'Урок урока',
        cabinet: 'Кабинет урока уроковича',
        current: 'Изучение урока',
        homeWork: 'Домашука урока уроковича',
        teacher: 'Клавида петровна',
        mark: 2,
      },
      {
        teacher: 'Клавида петровна',
        id: 1,
        lessonId: 5,
        callStart: '8:45',
        callEnd: '9:45',
        name: '31321dsa',
        cabinet: 'Кабінет географії[36]',
        current: '5',
        homeWork: '6',
        mark: 10,
      },
      {
        teacher: 'Клавида петровна',
        id: 1,
        lessonId: 5,
        callStart: '8:45',
        callEnd: '9:45',
        name: '31321dsa',
        cabinet: 'Кабінет географії[36]',
        current: '5',
        homeWork: '6',
        mark: 10,
      },
    ],
  },
  {
    id: 3,
    date: '08.06.24',
    subjects: [
      {
        teacher: 'Клавида петровна',
        id: 123,
        lessonId: 1,
        callStart: '8:45',
        callEnd: '9:45',
        name: 'Урок урока',
        cabinet: 'Кабинет урока уроковича',
        current: 'Изучение урока',
        homeWork: 'Домашука урока уроковича',
        mark: 2,
      },
      {
        teacher: 'Клавида петровна',
        id: 5,
        lessonId: 2,
        callStart: '8:45',
        callEnd: '9:45',
        name: '212qwdadwa',
        cabinet: '3',
        current: '4',
        homeWork: '5',
        mark: 9,
      },
      {
        teacher: 'Клавида петровна',
        id: 45,
        lessonId: 3,
        callStart: '8:45',
        callEnd: '78:45',
        name: '31321dsa',
        cabinet: 'Кабінеxzxxcz ії[36]',
        current: '44',
        homeWork: '44',
        mark: 6,
      },
      {
        id: 123,
        lessonId: 4,
        callStart: '8:45',
        callEnd: '9:45',
        name: 'Урок урока',
        cabinet: 'Кабинет урока уроковича',
        current: 'Изучение урока',
        homeWork: 'Домашука урока уроковича',
        teacher: 'Клавида петровна',
        mark: 2,
      },
      {
        teacher: 'Клавида петровна',
        id: 1,
        lessonId: 5,
        callStart: '8:45',
        callEnd: '9:45',
        name: '31321dsa',
        cabinet: 'Кабінет географії[36]',
        current: '5',
        homeWork: '6',
        mark: 10,
      },
      {
        teacher: 'Клавида петровна',
        id: 1,
        lessonId: 5,
        callStart: '8:45',
        callEnd: '9:45',
        name: '31321dsa',
        cabinet: 'Кабінет географії[36]',
        current: '5',
        homeWork: '6',
        mark: 10,
      },
    ],
  },
  {
    id: 3,
    date: '09.06.24',
    subjects: [
      {
        teacher: 'Клавида петровна',
        id: 123,
        lessonId: 1,
        callStart: '8:45',
        callEnd: '9:45',
        name: 'Урок урока',
        cabinet: 'Кабинет урока уроковича',
        current: 'Изучение урока',
        homeWork: 'Домашука урока уроковича',
        mark: 2,
      },
      {
        teacher: 'Клавида петровна',
        id: 5,
        lessonId: 2,
        callStart: '8:45',
        callEnd: '9:45',
        name: '212qwdadwa',
        cabinet: '3',
        current: '4',
        homeWork: '5',
        mark: 9,
      },
      {
        teacher: 'Клавида петровна',
        id: 45,
        lessonId: 3,
        callStart: '8:45',
        callEnd: '78:45',
        name: '31321dsa',
        cabinet: 'Кабінеxzxxcz ії[36]',
        current: '44',
        homeWork: '44',
        mark: 6,
      },
      {
        id: 123,
        lessonId: 4,
        callStart: '8:45',
        callEnd: '9:45',
        name: 'Урок урока',
        cabinet: 'Кабинет урока уроковича',
        current: 'Изучение урока',
        homeWork: 'Домашука урока уроковича',
        teacher: 'Клавида петровна',
        mark: 2,
      },
      {
        teacher: 'Клавида петровна',
        id: 1,
        lessonId: 5,
        callStart: '8:45',
        callEnd: '9:45',
        name: '31321dsa',
        cabinet: 'Кабінет географії[36]',
        current: '5',
        homeWork: '6',
        mark: 10,
      },
      {
        teacher: 'Клавида петровна',
        id: 1,
        lessonId: 5,
        callStart: '8:45',
        callEnd: '9:45',
        name: '31321dsa',
        cabinet: 'Кабінет географії[36]',
        current: '5',
        homeWork: '6',
        mark: 10,
      },
    ],
  },
]);

const marks = ref([
  {
    firstName: 'Денис',
    lastName: 'Квак',
    marks: [1, 2, 'H', '', 1, 10, 4],
  },
  {
    firstName: 'Денис',
    lastName: 'Замикула',
    marks: [1, 2, 'H', '', 1, 10, 4],
  },
  {
    firstName: 'Денис',
    lastName: 'Замикула',
    marks: [1, 2, 'H', 1, 1, 10, 4],
  },
]);
</script>

<template>
  <div>
      <authentication-form></authentication-form>
<!--    <MyHeader></MyHeader>-->
<!--    <div class="px-2">-->
<!--      <TimeTable :timeTable="days"></TimeTable>-->
<!--      <div class="lg:w-[680px]">-->
<!--        <DiaryElement :date="'2023-11-15'" :lessons="les" />-->
<!--        <set-marks-->
<!--          class="mt-5"-->
<!--          :subject-name="'Математика'"-->
<!--          :marks="marks as any"-->
<!--          :week-date="{ startWeekTIMESTAMP: '2023-11-15' }"-->
<!--        ></set-marks>-->
<!--      </div>-->
<!--    </div>-->
  </div>
</template>

<style scoped></style>
